name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  mobx: ^2.0.6
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.2.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
